# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion="${fml_range}" #mandatory (27 is current forge version)

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="ARR"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ldtteam/stylecolonies/issues/new/choose" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="stylecolonies" #mandatory

# The version number of the mod
version="${version}" #mandatory

# A display name for the mod
displayName="Stylecolonies" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecolonies.com" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="minecolonies_logo.png" #optional

# A text field displayed in the mod UI
credits="All the coffees!" #optional

# A text field displayed in the mod UI
authors="LDT Team" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Stylecolonies containts a bunch of approved Stylepacks for Minecolonies
'''

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.stylecolonies]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[${forgeMinVersion}, )" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.stylecolonies]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"
